### ISSUE TITLE
Yak 141 Join Issue

### ISSUE THREAD

**Issue by SmandwichGuy** [ControlNet/wt-data-project.web#21]
![image](https://github.com/ControlNet/wt-data-project.web/assets/132314447/5a9d42ab-062c-459a-9d62-dc226af3da67)

**Comment by ControlNet** [comment]
Thank you for pointing out this. It is not the join issue, and the reason is yak-4 is not collected from wt wiki. These vehicles are hidden in the second page. In the scripts, these vehicle information are collected for each tier and each nation, but if there are more than 200 vehicles in one tier for one nation, the extra links will be hidden in the next page, which is the problem that I previously assume there is only one page (this situation does not happen in 4 years ago). I see there are 20 vehicles (mostly in tier 1 and 2) are not collected now which is terrible.
![image](https://github.com/ControlNet/wt-data-project.web/assets/12800094/f52f70fc-effd-4faf-a397-c5862896c9f6)

Appreciate for this feedback, and now it is solved.
