### ISSUE TITLE
WT Data Project, Germany Aircraft incorrectly included in Soviet Data 

### ISSUE THREAD

**Issue by armablign** [ControlNet/wt-data-project.web#3]
I would just like to bring the issue to attention
That the data set for Germany Aviation is incorrect.

Firstly, you can see that there is 'no data' for BR 11.3 Germany.
(How can this be? There are 2 aircraft at 11.3)

I then checked the USSR data set, ('clicked' 11.0 and 11.3)
to show the vehicles at that data set.

In there, I see:
mig_23mla | MiG-23MLD | **USSR** | Aviation | 11.3 | 3218 | 59.62 | 1.8 | 2.76 | 0.04 | 0.08 | False | 244 | 260
mig_23mf_germany | MiG-23M | **USSR** | Aviation | 11 | 4119 | 49.27 | 1.01 | 1.04 | 0.09 | 0.1 | False | 238 | 330
mig-21_bis_sau | MiG-21bis | **USSR** | Aviation | **11** | 1835 | 56.89 | 1.63 | 2.16 | 0.18 | 0.23 | False | 238 | 320

The above is incorrect,
All 3 should be in German Data set.
Secondly, the mig-21_bis_sau is at **11.3**, not 11.0.

Currently the data project, shows that there is 'not data' for Germany 11.3, and little for 11.0.
This is because, their airplanes are being added to USSR data set.

I hope this can be addressed.
Kind regards

**Comment by ControlNet** [comment]
Hi armablign,

Thank you for your report. I found this error occurs after 2021/10/30. I'm working on fixing it.

**Comment by ControlNet** [comment]
It's solved in ControlNet/wt-data-project.data@da689b8b4fa21992de993da158156551fdfa53f1

**Comment by armablign** [comment]
Hey,

No problem at all, I'm glad I could be of any help.
What occurred in 2021/10/30, is it the way the data hook handles vehicle names, or is it how Gaijin/WT configured their implementation? 

Thank you also for fixing it :D !
Also thank you for making and spending time on this project
It is much appreciated.

**Comment by ControlNet** [comment]
Hi,

OK, so things are like this. We have 2 data sources, one is Thunderskill (for stats) and another is WarThunder official wiki (for BR, nation, etc). The problem is how to match the data in two sources.

In the scripts, the matching follows the rules:

1. Manually specified matching pairs. (for around 120 vehicles now)
2. Localization-based transform. (It works in most cases)
3. Name string similarity. (High possibility causes problem)

In previous, these vehicles failed to find the correct localization name and also failed in the similarity comparison. So I add the manual match to fix it.

**Comment by armablign** [comment]
Hey, just wanted to say that 'mig_29_9_12_germany' is listed under USSR currently.

Thanks again for this amazing project you are spending time on!

**Comment by ControlNet** [comment]
@armablign 
Fix in ControlNet/wt-data-project.data@6af112de0fb4d960503d09eff915d368629cefca
