### ISSUE TITLE
Color gradient for win rates is misleading

### ISSUE THREAD

**Issue by Jiaming-S** [ControlNet/wt-data-project.web#8]
The current color gradient for win rates is confusing. Win rates in the ~90% range are too visually similar to win rates in the ~20% range. 

<img width="83" alt="Screen Shot 2022-11-23 at 6 00 41 PM" src="https://user-images.githubusercontent.com/112342179/203677372-eb9957e4-dcc0-4d63-93d5-49e40cfbdc9e.png">
<img width="105" alt="Screen Shot 2022-11-23 at 6 00 55 PM" src="https://user-images.githubusercontent.com/112342179/203677400-83e61a2e-929d-4591-ba07-075075af5ae1.png">

**Comment by ControlNet** [comment]
That's a good point, but I cannot find a better color encoding for it.

Could you please suggest a better solution?

The current status is like this.

## For `Ground_vehicles` + `win_rate`,
```js
const percentiles = [0, 0.05, 0.4, 0.5, 0.6, 0.95, 1.0];
const colors = [WHITE, BLACK, RED, YELLOW, GREEN, BLACK, BLACK];
```

![image](https://user-images.githubusercontent.com/12800094/203681313-f2a987fd-5850-40e3-885a-419771978402.png)


## For `Aviation` + `win_rate`,
```js
const percentiles = [0, 0.01, 0.5, 0.6, 0.7, 0.99, 1.0];
const colors = [WHITE, BLACK, RED, YELLOW, GREEN, BLACK, BLACK];
```

![image](https://user-images.githubusercontent.com/12800094/203681823-13c6dc21-74e7-438d-94c2-e0701e7325df.png)


## For counting `battles_sum`

```js
const percentiles = [0, 0.01, 0.4, 0.5, 0.6, 0.99, 1.0];
const colors = [WHITE, BLACK, RED, YELLOW, GREEN, BLACK, BLACK];
```

![image](https://user-images.githubusercontent.com/12800094/203682166-7b0cc7cb-1104-4e55-b1b3-bdfb384f6d58.png)


PS: You can use the following python script to generate the colorbar.
```python
WHITE = "#EEFFFF"
BLACK = "#2B2B2B"
RED = "#D11141"
YELLOW = "#FFC425"
GREEN = "#00B159"

percentiles = [0, 0.05, 0.4, 0.5, 0.6, 0.95, 1.0]
colors = [WHITE, BLACK, RED, YELLOW, GREEN, BLACK, BLACK]

# -----------------------------------------

import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.colors import LinearSegmentedColormap


fig, ax = plt.subplots(figsize=(12, 1.5))
cmap = LinearSegmentedColormap.from_list("new_colormap", list(zip(percentiles, colors)))
cb2 = mpl.colorbar.ColorbarBase(ax, cmap=cmap,
                                ticks=percentiles,
                                spacing='proportional',
                                orientation='horizontal')
fig.show()
```

**Comment by Jiaming-S** [comment]
So this turned out to be more difficult than expected, nevertheless here's some that I found successful:

This first gradient solves the color blending problem by including a third color, there's still a bit of semi-ambiguous coloring near the middle but they can mostly be distinguished by the red/blue hues 
```python
C1 = '#BB0000' # red on far left
C2 = '#BB3300' 
C3 = '#888800' 
C4 = '#00AA00' # green in middle
C5 = '#008888' 
C6 = '#0033BB' 
C7 = '#0000FF' # blue on far right

percentiles = [0.0, 0.2, 0.4, 0.5, 0.6, 0.8, 1.0]
colors      = [C1,  C2,  C3,  C4,  C5,  C6,  C7]
```
<img width="768" alt="Screen Shot 2022-11-23 at 7 48 25 PM" src="https://user-images.githubusercontent.com/112342179/203689690-336ea0d8-ee65-4c87-8089-cf53131fae94.png"> 
  
This second one only uses two colors but solves color blending by making the left hues of green darker and the right hues of green lighter
```python
C1 = '#FF0000' ### red on far left
C2 = '#883300' 
C3 = '#338800' 
C4 = '#00AA00' ### green in middle
C5 = '#33CC33' 
C6 = '#88CC88' 
C7 = '#FFFFFF' ### white on far right

percentiles = [0.0, 0.2, 0.4, 0.5, 0.6, 0.8, 1.0]
colors      = [C1,  C2,  C3,  C4,  C5,  C6,  C7]
```
<img width="782" alt="Screen Shot 2022-11-23 at 8 12 15 PM" src="https://user-images.githubusercontent.com/112342179/203692640-d7fd9d7e-f6cb-41ca-9b14-e63b8f270e55.png">

Last one I tried was a more standard looking color gradient with two colors, however since most win rates hover around the 50% mark, most of them will look like a sad yellow color
```python
C1 = '#FF0000' 
C2 = '#FF3300' 
C3 = '#FF8800' 
C4 = '#FFBB33' 
C5 = '#AABB33' 
C6 = '#88BB33' 
C7 = '#33FF33' 

percentiles = [0.0, 0.2, 0.4, 0.5, 0.6, 0.8, 1.0]
colors      = [C1,  C2,  C3,  C4,  C5,  C6,  C7]
```

<img width="784" alt="Screen Shot 2022-11-23 at 8 35 02 PM" src="https://user-images.githubusercontent.com/112342179/203695111-1d324a20-1bb9-4eef-9773-85b2539de31e.png">

**Comment by ControlNet** [comment]
Here are the results when I deploy these 3 color maps to `Ground_vehicles` + `win_rate`.

For the first gradient,
![image](https://user-images.githubusercontent.com/12800094/203705595-b959a34f-4d69-4294-8293-568b366c409b.png)

For the second gradient,
![image](https://user-images.githubusercontent.com/12800094/203705970-ca27932e-3a21-4b39-9a03-d29f1b1d700d.png)

For the third gradient,
![image](https://user-images.githubusercontent.com/12800094/203706092-5253a23a-0746-4004-aa13-bc849c3498bc.png)


In my opinion, they're all not good. It also explains that why I put the color gradients squeezed like that.

**Comment by Skasi** [comment]
So the trick is changing color exponentially. The closer we get to 0.5 the stronger the color shift should be. However we also want to broaden the spectrum. I came up with this using HSL values. (see [this jsfiddle example](https://jsfiddle.net/L06wcgus/54/))

Values used in the format `(hue, saturation, lightness) percentile`:
```
hsl(240,   0%,  0%) 0%,
hsl(270, 100%, 40%) 2%,
hsl(300, 100%, 40%) 26%,
hsl(330, 100%, 40%) 38%,
hsl(  0, 100%, 40%) 44%,
hsl( 30, 100%, 40%) 47%,
hsl( 60, 100%, 40%) 50%,
hsl( 90, 100%, 40%) 53%,
hsl(120, 100%, 40%) 56%,
hsl(150, 100%, 40%) 62%,
hsl(180, 100%, 40%) 74%,
hsl(210, 100%, 40%) 98%,
hsl(240,   0%, 50%) 100%
```

Note that it's imperfect since I'm using a linear gradient. Ideally there would be more steps, but the original version has the same issue.

![example graph](https://user-images.githubusercontent.com/132906/203776339-eca1b4fc-796f-44bd-8871-6f1e4976fa36.png)

**Comment by ControlNet** [comment]
For the first gradient, I adjust the gradient as below to fit the distribution of the heatmap values.
```js
const percentile = [0, 0.03, 0.31, 0.46, 0.51, 0.54, 0.6, 0.63, 0.68, 0.74, 0.81, 0.97, 1]
```
And now it looks like this.
![image](https://user-images.githubusercontent.com/12800094/203833938-14c2fdc9-85ca-40ff-84c6-ce747e82a70f.png)


I feel it's still confusing. I assume the users want to observe the difference and compare by the change of saturation/lightness rather than hue.  So squeezing so many colors to represent the different kinds of conditions (very low: purple, low: red, medium: yellow, high: green, very high: blue) in the color map might not be a good idea. 

In the current implementation, except white is used to present the special case (value = 0), only 3 types of color is used to represent the rough condition (low: red, medium: yellow, high: green), and inside one condition, for example comparing 0.6 with 0.9, the main difference is Lightness (I use HSL colormap for interpolation). 

I understand the confusion between very high value and very low value because they all look black, and I also want to improve it as well.  But it's totally not unusable because users can infer from the neighbors' colors.

The colormap definition is in 
https://github.com/ControlNet/wt-data-project.web/blob/745c6f0daa483f33bf60a4af876a5582b64d9f91/src/plot/br-heatmap.ts#L314-L317

Please feel free to do experiments and suggest a better solution.

**Comment by Skasi** [comment]
> I assume the users want to observe the difference and compare by the change of saturation/lightness rather than hue.

Is that assumption correct though? [People seem to want more colors.](https://www.reddit.com/r/Warthunder/comments/z33flo/are_we_witnessing_a_power_shift/)

**Comment by ControlNet** [comment]
@Skasi 
> The closer we get to 0.5 the stronger the color shift should be

Actually no. Because of the bias of the distribution of thunderskill users and the whole warthunder players, the medium point of the gradient should not be near 0.5. Empirically, I set 0.6 for `win_rate` and 0.5 for `battles_sum`.

**Comment by Skasi** [comment]
I see. Well whatever the number may be, the main point I wanted to convey was that the color shifts should be stronger the closer to the point you get. This is to "zoom in" or "inflate" the area where most vehicles would statistically fall into and to prevent the majority of cells being yellow-ish.

**Comment by ControlNet** [comment]
@Skasi 

Oh, I don't know this thread. 

> [People seem to want more colors.](https://www.reddit.com/r/Warthunder/comments/z33flo/are_we_witnessing_a_power_shift/)

We should say, people want more differentiable colors.

I totally agree with what they mentioned. Let me work on it and will update later.

> yea kinda true, sadly cant do anything about it

BTW, I think I should have a better place for communicating about the project. I just setup the Github discussion and hope people can see it.

**Comment by ControlNet** [comment]
@Skasi 
> being yellow-ish

I feel the gradient near the medium value is not bad. The main problem is that 10% and 90% give a very similar black color. I can start working on it first.

**Comment by ControlNet** [comment]
@Jiaming-S @Skasi 
I finally get it. It's because I'm using buggy interpolation.
![image](https://user-images.githubusercontent.com/12800094/203859420-ac8a7129-c6a0-4b89-a530-405cd52eccc9.png)

So you see, the transition is from RED then DARK GREEN then BLACK, which is totally problematic.

To solve it, I test using `d3.interpolateHsl` to replace `d3.interpolateHcl`. And this is the comparison.
![image](https://user-images.githubusercontent.com/12800094/203859692-1668fa4b-ff74-4e06-bcba-d6a30299b53d.png)

Now it looks much better.

**Comment by ControlNet** [comment]
Implemented in https://github.com/ControlNet/wt-data-project.web/commit/02dcd9d4e41017d8bad15abcf32c8429fd5f9220 .
